[package]
name = "chip_8_emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytebuffer = "2.2.0"
clap = { version = "4.4.12", features = ["derive"] }
thiserror = "1.0.53"
